const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const store=require('../control-tower-state');const runtime=require('../control-tower-runtime');
function file(){return path.join(fs.mkdtempSync(path.join(os.tmpdir(),'parma-ct-')),'state.json')}
function init(f,tasks){store.save(store.newState({goal:'goal',tasks}),f)}
test('safe task A continues to B without prompt',async()=>{const f=file();const seen=[];init(f,[{id:'a',kind:'run_diagnostics',change:{},max_attempts:2},{id:'b',kind:'generate_report',depends_on:['a'],change:{},max_attempts:2}]);const ex={run_diagnostics:async t=>{seen.push(t.id);return{level1_passed:true,level2_passed:true}},generate_report:async t=>{seen.push(t.id);return{level1_passed:true,level2_passed:true}}};const s=await runtime.runUntilStop({file:f,executors:ex});assert.deepEqual(seen,['a','b']);assert.equal(s.status,'DONE')});
test('restart resumes persisted unfinished goal',async()=>{const f=file();init(f,[{id:'a',kind:'run_diagnostics',change:{},max_attempts:2},{id:'b',kind:'generate_report',depends_on:['a'],change:{},max_attempts:2}]);let first=true;await runtime.runUntilStop({file:f,maxSteps:1,executors:{run_diagnostics:async()=>{if(first){first=false;return{level1_passed:true,level2_passed:true}}},generate_report:async()=>({level1_passed:true,level2_passed:true})}});let s=store.load(f).state;s.status='NEXT';store.save(s,f);const done=await runtime.runUntilStop({file:f,executors:{run_diagnostics:async()=>({level1_passed:true,level2_passed:true}),generate_report:async()=>({level1_passed:true,level2_passed:true})}});assert.equal(done.tasks.every(t=>t.status==='done'),true);assert.equal(done.status,'DONE')});
test('idempotency key prevents duplicate completed execution',async()=>{const f=file();init(f,[{id:'a',kind:'run_diagnostics',idempotency_key:'k1',change:{}}]);let n=0;let s=store.load(f).state;s.events.push({type:'task_completed',task_id:'old',idempotency_key:'k1',at:new Date().toISOString()});store.save(s,f);const done=await runtime.runUntilStop({file:f,executors:{run_diagnostics:async()=>{n++;return{level1_passed:true,level2_passed:true}}}});assert.equal(n,0);assert.equal(done.status,'DONE')});
test('bounded retries stop after max attempts',async()=>{const f=file();init(f,[{id:'a',kind:'run_diagnostics',change:{},max_attempts:2}]);let n=0;const s=await runtime.runUntilStop({file:f,executors:{run_diagnostics:async()=>{n++;return{level1_passed:false,level2_passed:false,reason:'bad'}}}});assert.equal(n,2);assert.equal(s.status,'BLOCKED_EXTERNAL')});
test('authorization-required action stops before executor',async()=>{const f=file();init(f,[{id:'x',kind:'activate_campaign'}]);let ran=false;const s=await runtime.runUntilStop({file:f,executors:{activate_campaign:async()=>{ran=true}}});assert.equal(ran,false);assert.equal(s.status,'NEEDS_HUMAN')});
test('corrupt state fails closed and is not overwritten',async()=>{const f=file();fs.writeFileSync(f,'{bad');await assert.rejects(()=>runtime.runUntilStop({file:f}),/autonomous_state_corrupt/);assert.equal(fs.readFileSync(f,'utf8'),'{bad')});
test('secret-shaped state rejected',()=>assert.throws(()=>store.save({...store.newState({goal:'x'}),credential:'x'},file()),/secret_shaped_state_rejected/));
test('concurrent lock contention fails closed',()=>{const f=file();init(f,[]);store.withLock(f,()=>assert.throws(()=>store.update(f,s=>s),/autonomous_state_locked/))});
test('storage is durable only when explicit path or Railway volume is non tmp',()=>{assert.equal(store.storageStatus({}).durable,false);assert.equal(store.storageStatus({RAILWAY_VOLUME_MOUNT_PATH:'/data'}).durable,true)});
