const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const store=require('../control-tower-state');const runtime=require('../control-tower-runtime');
function file(){return path.join(fs.mkdtempSync(path.join(os.tmpdir(),'parma-ct-')),'state.json')}
function init(f,tasks){store.save(store.newState({goal:'goal',tasks}),f)}
test('safe task A continues to B without prompt',async()=>{const f=file();const seen=[];init(f,[{id:'a',kind:'run_diagnostics',change:{},max_attempts:2},{id:'b',kind:'generate_report',depends_on:['a'],change:{},max_attempts:2}]);const ex={run_diagnostics:async t=>{seen.push(t.id);return{level1_passed:true,level2_passed:true}},generate_report:async t=>{seen.push(t.id);return{level1_passed:true,level2_passed:true}}};const s=await runtime.runUntilStop({file:f,executors:ex});assert.deepEqual(seen,['a','b']);assert.equal(s.status,'DONE')});
test('restart resumes persisted unfinished goal',async()=>{const f=file();init(f,[{id:'a',kind:'run_diagnostics',change:{},max_attempts:2},{id:'b',kind:'generate_report',depends_on:['a'],change:{},max_attempts:2}]);await runtime.runUntilStop({file:f,maxSteps:1,executors:{run_diagnostics:async()=>({level1_passed:true,level2_passed:true}),generate_report:async()=>({level1_passed:true,level2_passed:true})}});let s=store.load(f).state;s.status='NEXT';store.save(s,f);const done=await runtime.runUntilStop({file:f,executors:{run_diagnostics:async()=>({level1_passed:true,level2_passed:true}),generate_report:async()=>({level1_passed:true,level2_passed:true})}});assert.equal(done.tasks.every(t=>t.status==='done'),true);assert.equal(done.status,'DONE')});
test('idempotency key prevents duplicate completed execution',async()=>{const f=file();init(f,[{id:'a',kind:'run_diagnostics',idempotency_key:'k1',change:{}}]);let n=0;let s=store.load(f).state;s.events.push({type:'task_completed',task_id:'old',idempotency_key:'k1',at:new Date().toISOString()});store.save(s,f);const done=await runtime.runUntilStop({file:f,executors:{run_diagnostics:async()=>{n++;return{level1_passed:true,level2_passed:true}}}});assert.equal(n,0);assert.equal(done.status,'DONE')});
test('preserves original task metadata for risk and idempotency',async()=>{const f=file();init(f,[{id:'a',kind:'run_diagnostics',idempotency_key:'custom',change:{autonomy_logic:true}}]);let got;const s=await runtime.runUntilStop({file:f,executors:{run_diagnostics:async(t,c)=>{got={key:t.idempotency_key,live:c.validation.live_read_only_validation};return{level1_passed:true,level2_passed:false}}},validators:{live:async()=>({passed:true})}});assert.deepEqual(got,{key:'custom',live:true});assert.equal(s.status,'DONE')});
test('bounded retries stop after max attempts',async()=>{const f=file();init(f,[{id:'a',kind:'run_diagnostics',change:{},max_attempts:2}]);let n=0;const s=await runtime.runUntilStop({file:f,executors:{run_diagnostics:async()=>{n++;return{level1_passed:false,level2_passed:false,reason:'bad'}}}});assert.equal(n,2);assert.equal(s.status,'BLOCKED_EXTERNAL')});
test('authorization-required action stops before executor',async()=>{const f=file();init(f,[{id:'x',kind:'activate_campaign'}]);let ran=false;const s=await runtime.runUntilStop({file:f,executors:{activate_campaign:async()=>{ran=true}}});assert.equal(ran,false);assert.equal(s.status,'NEEDS_HUMAN')});
test('live evidence deficiency is repaired by L2 validator then execution continues',async()=>{const f=file();init(f,[{id:'a',kind:'run_diagnostics',change:{}}]);let validated=0,executed=0;const s=await runtime.runUntilStop({file:f,context:{fresh_enough:false},validators:{live:async()=>{validated++;return{passed:true}}},executors:{run_diagnostics:async()=>{executed++;return{level1_passed:true,level2_passed:true}}}});assert.equal(validated,1);assert.equal(executed,1);assert.equal(s.status,'DONE')});
test('concurrent runtime does not duplicate leased execution',async()=>{const f=file();init(f,[{id:'a',kind:'run_diagnostics',change:{}}]);let release,n=0;const gate=new Promise(r=>{release=r});const first=runtime.runUntilStop({file:f,ownerId:'one',leaseMs:60000,executors:{run_diagnostics:async()=>{n++;await gate;return{level1_passed:true,level2_passed:true}}}});while(store.load(f).state.tasks[0].status!=='running')await new Promise(r=>setTimeout(r,1));const second=await runtime.runUntilStop({file:f,ownerId:'two',executors:{run_diagnostics:async()=>{n++;return{level1_passed:true,level2_passed:true}}}});assert.equal(second.status,'EXECUTE');assert.equal(n,1);release();const done=await first;assert.equal(done.status,'DONE');assert.equal(n,1)});
test('expired lease after crash is recovered and retried',async()=>{const f=file();init(f,[{id:'a',kind:'run_diagnostics',change:{},max_attempts:3}]);store.claimTask(f,'a','dead',{now:0,leaseMs:1});let s=store.load(f).state;s.tasks[0].lease_expires_at=new Date(1).toISOString();store.save(s,f);let n=0;const done=await runtime.runUntilStop({file:f,executors:{run_diagnostics:async()=>{n++;return{level1_passed:true,level2_passed:true}}}});assert.equal(n,1);assert.equal(done.status,'DONE');assert.equal(done.tasks[0].attempts,1)});
test('corrupt state fails closed and is not overwritten',async()=>{const f=file();fs.writeFileSync(f,'{bad');await assert.rejects(()=>runtime.runUntilStop({file:f}),/autonomous_state_corrupt/);assert.equal(fs.readFileSync(f,'utf8'),'{bad')});
test('secret-shaped state rejected',()=>assert.throws(()=>store.save({...store.newState({goal:'x'}),credential:'x'},file()),/secret_shaped_state_rejected/));
test('concurrent lock contention fails closed',()=>{const f=file();init(f,[]);store.withLock(f,()=>assert.throws(()=>store.update(f,s=>s),/autonomous_state_locked/))});
test('storage is durable only when explicit path or Railway volume is non tmp',()=>{assert.equal(store.storageStatus({}).durable,false);assert.equal(store.storageStatus({RAILWAY_VOLUME_MOUNT_PATH:'/data'}).durable,true)});
