'use strict';
const test=require('node:test'),assert=require('node:assert/strict');const fs=require('node:fs'),os=require('node:os'),path=require('node:path');const {randomBytes}=require('node:crypto');
const {ExecutionLedger}=require('../google-controlled-executor');const {CANDIDATES,validCandidate,executeOne,rollbackOne}=require('../google-controlled-negative');
function fixture(t){const root=fs.mkdtempSync(path.join(os.tmpdir(),'negative-exec-')),dir=path.join(root,'ledger');fs.mkdirSync(dir,{mode:0o700});t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const ledger=new ExecutionLedger({directory:dir,integrityKey:randomBytes(32)});let present=false,budget=7500000,calls=[];
 const customer={query:async q=>{if(q.includes('FROM customer'))return[{customer:{id:'7376153998',currency_code:'EUR',time_zone:'Europe/Berlin'}}];if(q.includes('campaign.advertising_channel_type'))return[{campaign:{id:'23276824770',name:'Dinner',status:'ENABLED',advertising_channel_type:'SEARCH',campaign_budget:'customers/7376153998/campaignBudgets/1'},campaign_budget:{resource_name:'customers/7376153998/campaignBudgets/1',amount_micros:3500000,explicitly_shared:false}},{campaign:{id:'23853417314',name:'Late',status:'ENABLED',advertising_channel_type:'SEARCH',campaign_budget:'customers/7376153998/campaignBudgets/2'},campaign_budget:{resource_name:'customers/7376153998/campaignBudgets/2',amount_micros:budget-3500000,explicitly_shared:false}}];if(q.includes('FROM search_term_view'))return[{search_term_view:{search_term:'sly restaurant berlin'},segments:{date:'2026-09-03'},metrics:{impressions:1,clicks:1,cost_micros:4970000}}];if(q.includes('FROM campaign_criterion'))return present?[{campaign_criterion:{resource_name:'customers/7376153998/campaignCriteria/23853417314~99',keyword:{text:'sly restaurant berlin',match_type:'EXACT'}}}]:[];if(q.includes('FROM ad_group_criterion'))return[];throw Error('unexpected query');}};
 const adapter={mutate:async(op,opt)=>{calls.push({op,opt});if(!opt.validate_only)present=op.type==='create';return{results:op.type==='create'?[{resourceName:'customers/7376153998/campaignCriteria/23853417314~99'}]:[]};}};
 return{customer,adapter,ledger,candidate:CANDIDATES[0],calls,getPresent:()=>present,setBudget:v=>budget=v,now:()=>Date.parse('2026-09-04T20:00:00.000Z')};}
test('only exact unprotected verified-other-restaurant candidate is valid',()=>{assert.equal(validCandidate(CANDIDATES[0]),true);for(const text of ['pizza near me','pizza in meiner nähe','pizza kreuzberg','Parma'])assert.equal(validCandidate({...CANDIDATES[0],text}),false);assert.equal(validCandidate({...CANDIDATES[0],match_type:'PHRASE'}),false);assert.equal(validCandidate({...CANDIDATES[0],semantic_class:'ambiguous'}),false);});
test('validate, execute once, read after write and keep budgets',async t=>{const f=fixture(t);const r=await executeOne(f);assert.equal(r.status,'verified');assert.equal(r.budget_before_micros,7500000);assert.equal(r.budget_after_micros,7500000);assert.equal(r.rollback_available,true);assert.deepEqual(f.calls.map(x=>x.opt.validate_only),[true,false]);assert.equal((await executeOne(f)).replayed,true);assert.equal(f.calls.length,2);});
test('budget drift after validation blocks before write',async t=>{const f=fixture(t);let count=0,orig=f.customer.query;f.customer.query=async q=>{if(q.includes('campaign.advertising_channel_type')&&++count===2)f.setBudget(7600000);return orig(q);};await assert.rejects(executeOne(f),/preflight_state_changed/);assert.equal(f.calls.length,1);});
test('kill switch blocks before provider validation',async t=>{const f=fixture(t);await assert.rejects(executeOne({...f,killSwitch:async()=>true}),/kill_switch/);assert.equal(f.calls.length,0);});
test('rollback validates, removes exact created resource and verifies absence',async t=>{const f=fixture(t);const made=await executeOne(f);const r=await rollbackOne({...f,sourceId:made.id});assert.equal(r.status,'verified');assert.equal(f.getPresent(),false);assert.deepEqual(f.calls.map(x=>x.opt.validate_only),[true,false,true,false]);});
