'use strict';
const test=require('node:test');const assert=require('node:assert/strict');
const {auditInstagramContentCapability,auditInstagramLoginCapability,buildContainerPayload,createMediaContainer,getContainerStatus,publishMedia,verifyPublishedMedia,readMediaInsights}=require('../instagram-content-publishing');

function transport({permissions=true,insights=true,pagesDirect=false}={}){
 const calls=[];return {calls,
  async get(path,params){calls.push({method:'GET',path,params});if(path==='/me/permissions'){if(!permissions)throw new Error('denied');return {data:['instagram_basic','pages_show_list','pages_read_engagement','instagram_manage_insights','instagram_content_publish'].map(permission=>({permission,status:'granted'}))};}if(path==='/me/accounts'){if(pagesDirect)return {data:[{id:'20',name:'Parma',instagram_business_account:{id:'30',username:'parma.divinibenedetti'}}]};throw new Error('denied');}if(path==='/act_1')return {business:{id:'10'}};if(path==='/10/owned_pages')return {data:[{id:'20',name:'Parma',instagram_business_account:{id:'30',username:'parma.divinibenedetti'}}]};if(path==='/30/media')return {data:[{id:'40',media_type:'VIDEO',media_product_type:'REELS'}]};if(path==='/30/insights'){if(!insights)throw new Error('denied');return {data:[]};}if(path==='/50')return {id:'50',status_code:'FINISHED'};if(path==='/60')return {id:'60',permalink:'https://www.instagram.com/reel/example/',media_type:'VIDEO',media_product_type:'REELS'};if(path==='/60/insights')return {data:[{name:'reach',values:[{value:42}]}]};throw new Error(`unexpected ${path}`);},
  async post(path,payload){calls.push({method:'POST',path,payload});return path.endsWith('/media_publish')?{id:'60'}:{id:'50'};}
 };
}
test('live audit proves account, linked Page, media, insights and publishing permission without writes',async()=>{const t=transport();const r=await auditInstagramContentCapability({transport:t,adAccountId:'act_1'});assert.equal(r.capabilities.publish,true);assert.equal(r.capabilities.stories,true);assert.equal(r.inventory.media_count,1);assert.equal(r.contains_secret,false);assert.equal(t.calls.some(x=>x.method==='POST'),false);});
test('audit discovers Instagram from user pages without Ads access',async()=>{const t=transport({pagesDirect:true});const r=await auditInstagramContentCapability({transport:t});assert.equal(r.capabilities.read_account,true);assert.equal(r.capabilities.publish,true);assert.equal(t.calls.some(x=>x.path.startsWith('/act_')),false);});
test('Instagram Login audit reads the professional account directly without Facebook Page or Ads',async()=>{const calls=[];const t={get:async(path)=>{calls.push(path);if(path==='/me')return{id:'30',user_id:'30',username:'parma.divinibenedetti',account_type:'BUSINESS'};if(path==='/me/media')return{data:[{id:'40',media_product_type:'REELS'}]};if(path==='/me/insights')return{data:[]};throw new Error('unexpected');}};const r=await auditInstagramLoginCapability({transport:t});assert.equal(r.capabilities.read_account,true);assert.equal(r.capabilities.publish,'SUPPORTED_NOT_YET_TESTED');assert.deepEqual(calls,['/me','/me/media','/me/insights']);});
test('audit fails closed when permissions cannot be enumerated',async()=>{const r=await auditInstagramContentCapability({transport:transport({permissions:false}),adAccountId:'act_1'});assert.equal(r.capabilities.read_media,true);assert.equal(r.capabilities.publish,false);assert.ok(r.blockers.includes('instagram_content_publish_not_verified'));});
test('Reel and Story payloads validate public HTTPS media and caption contract',()=>{assert.deepEqual(buildContainerPayload({videoUrl:'https://cdn.example/reel.mp4',caption:'Ciao'}),{media_type:'REELS',video_url:'https://cdn.example/reel.mp4',caption:'Ciao',share_to_feed:true});assert.deepEqual(buildContainerPayload({mediaType:'STORIES',videoUrl:'https://cdn.example/story.mp4'}),{media_type:'STORIES',video_url:'https://cdn.example/story.mp4'});assert.throws(()=>buildContainerPayload({videoUrl:'http://bad/reel.mp4'}),/HTTPS/);assert.throws(()=>buildContainerPayload({mediaType:'STORIES',videoUrl:'https://cdn.example/x.mp4',caption:'no'}),/does not accept caption/);});
test('container, publish, verification and insights use the expected Graph contracts',async()=>{const t=transport();assert.deepEqual(await createMediaContainer({transport:t,instagramUserId:'30',videoUrl:'https://cdn.example/reel.mp4',caption:'Hi'}),{id:'50'});assert.equal((await getContainerStatus({transport:t,containerId:'50'})).ready,true);assert.deepEqual(await publishMedia({transport:t,instagramUserId:'30',containerId:'50'}),{id:'60'});assert.equal((await verifyPublishedMedia({transport:t,mediaId:'60'})).published,true);assert.equal((await readMediaInsights({transport:t,mediaId:'60'})).data[0].values[0].value,42);});
