const test=require('node:test');const assert=require('node:assert/strict');const {inspectNamedDraftChain,runMetaRealPreflight}=require('../meta-real-preflight');
const draft={campaign:{name:'Parma Test',objective:'OUTCOME_TRAFFIC',status:'PAUSED'},adSet:{lifetime_budget:8400,status:'PAUSED',targeting:{publisher_platforms:['instagram']},dsa_beneficiary:'Parma',dsa_payor:'Parma'},creative:{name:'Parma Creative',object_id:'p',instagram_user_id:'i',source_instagram_media_id:'m'},ad:{status:'PAUSED'},policy:{may_activate:false}};const assets={page_id:'p',instagram_user_id:'i',source_instagram_media_id:'m'};
function transport(routes){return{get:async(path)=>routes[path]||{data:[]}}}
test('empty account chain is safe and read only',async()=>{const r=await runMetaRealPreflight({transport:transport({'/act_1/campaigns':{data:[]}}),adAccountId:'act_1',draft,assets,writeGateEnabled:true,approvalTokenOk:true});assert.equal(r.ready,true);assert.equal(r.may_spend,false);assert.equal(r.maximum_attempts,1)});
test('duplicate named campaigns block execution',async()=>{const t=transport({'/act_1/campaigns':{data:[{id:'1',name:'Parma Test',status:'PAUSED',objective:'OUTCOME_TRAFFIC'},{id:'2',name:'Parma Test',status:'PAUSED',objective:'OUTCOME_TRAFFIC'}]}});const r=await runMetaRealPreflight({transport:t,adAccountId:'act_1',draft,assets,writeGateEnabled:true,approvalTokenOk:true});assert.equal(r.ready,false);assert.ok(r.blockers.includes('duplicate_campaigns'))});
test('active partial campaign blocks recovery',async()=>{const t=transport({'/act_1/campaigns':{data:[{id:'1',name:'Parma Test',status:'ACTIVE',objective:'OUTCOME_TRAFFIC'}]}});const r=await inspectNamedDraftChain({transport:t,adAccountId:'act_1',draft});assert.equal(r.safe,false);assert.ok(r.blockers.includes('campaign_not_resumable'))});
test('paused campaign and adset are reused without writes',async()=>{const t=transport({'/act_1/campaigns':{data:[{id:'1',name:'Parma Test',status:'PAUSED',objective:'OUTCOME_TRAFFIC'}]},'/1/adsets':{data:[{id:'2',status:'PAUSED',campaign_id:'1'}]},'/2/ads':{data:[]}});const r=await inspectNamedDraftChain({transport:t,adAccountId:'act_1',draft});assert.equal(r.safe,true);assert.equal(r.knownPartial.campaign_id,'1');assert.equal(r.knownPartial.adset_id,'2')});
test('existing matching creative is reused even before ad exists',async()=>{const t=transport({'/act_1/campaigns':{data:[]},'/act_1/adcreatives':{data:[{id:'9',name:'Parma Creative',object_id:'p',instagram_user_id:'i'}]}});const r=await inspectNamedDraftChain({transport:t,adAccountId:'act_1',draft});assert.equal(r.safe,true);assert.equal(r.knownPartial.creative_id,'9')});
test('duplicate creatives block one-shot to avoid another duplicate',async()=>{const t=transport({'/act_1/campaigns':{data:[]},'/act_1/adcreatives':{data:[{id:'8',name:'Parma Creative'},{id:'9',name:'Parma Creative'}]}});const r=await inspectNamedDraftChain({transport:t,adAccountId:'act_1',draft});assert.equal(r.safe,false);assert.ok(r.blockers.includes('duplicate_creatives'))});
test('adset parent mismatch fails closed',async()=>{const t=transport({'/act_1/campaigns':{data:[{id:'1',name:'Parma Test',status:'PAUSED',objective:'OUTCOME_TRAFFIC'}]},'/1/adsets':{data:[{id:'2',status:'PAUSED',campaign_id:'999'}]}});const r=await inspectNamedDraftChain({transport:t,adAccountId:'act_1',draft});assert.equal(r.safe,false);assert.ok(r.blockers.includes('adset_campaign_mismatch'))});
test('ad creative mismatch fails closed',async()=>{const t=transport({'/act_1/campaigns':{data:[{id:'1',name:'Parma Test',status:'PAUSED',objective:'OUTCOME_TRAFFIC'}]},'/act_1/adcreatives':{data:[{id:'9',name:'Parma Creative',object_id:'p',instagram_user_id:'i'}]},'/1/adsets':{data:[{id:'2',status:'PAUSED',campaign_id:'1'}]},'/2/ads':{data:[{id:'3',status:'PAUSED',adset_id:'2',creative:{id:'77'}}]}});const r=await inspectNamedDraftChain({transport:t,adAccountId:'act_1',draft});assert.equal(r.safe,false);assert.ok(r.blockers.includes('ad_creative_mismatch'))});
