'use strict';
const test=require('node:test');const assert=require('node:assert/strict');const fs=require('node:fs');const os=require('node:os');const path=require('node:path');const crypto=require('node:crypto');const vm=require('node:vm');
const source=fs.readFileSync(path.join(__dirname,'../personal-os-step3-store.js'),'utf8');const moduleFixture={exports:{}};vm.runInNewContext(source,{Buffer,process,module:moduleFixture,exports:moduleFixture.exports,require:id=>id==='./personal-os-runtime-handoff'?{publishRuntimeHandoff:()=>{}}:require(id)});
const {taskSchema,Step3Store,digest}=moduleFixture.exports;
const task={schema_version:'personal_os.remote_procedure.v1',request_id:'EVIDENCE-QUERY-TEST',issued_at:'2026-10-09T08:00:00.000Z',workspace:'personal-os-control',procedure_id:'step7.evidence.read',parameters:{request_id:'PROVIDER-READ-TEST'}};
test('STEP3 accepts only correlated identifier input for bounded evidence read',()=>{assert.equal(taskSchema.safeParse(task).success,true);for(const parameters of [{},{request_id:'../private'},{request_id:'GOOD',path:'/etc/passwd'},{request_id:'GOOD',handoff_id:'OTHER'},{request_id:3}])assert.equal(taskSchema.safeParse({...task,parameters}).success,false);assert.equal(taskSchema.safeParse({...task,procedure_id:'local.report',parameters:{}}).success,true);assert.equal(taskSchema.safeParse({...task,procedure_id:'google_ads.write'}).success,false);});
test('existing verified ACK store preserves sanitized CURRENT evidence and does not promote ACK alone',t=>{
 const root=fs.mkdtempSync(path.join(os.tmpdir(),'step7-cloud-evidence-'));t.after(()=>fs.rmSync(root,{recursive:true,force:true}));const cloud=crypto.generateKeyPairSync('ed25519'),mac=crypto.generateKeyPairSync('ed25519');
 const store=new Step3Store({PERSONAL_OS_STEP3_STATE_PATH:root,PERSONAL_OS_STEP3_TASK_SIGNING_PRIVATE_KEY_PEM:cloud.privateKey.export({type:'pkcs8',format:'pem'}),PERSONAL_OS_STEP3_MAC_PUBLIC_KEY_PEM:mac.publicKey.export({type:'spki',format:'pem'}),PERSONAL_OS_STEP3_EXECUTOR_ID:'TEST-CLOUD',PERSONAL_OS_STEP3_TASK_KEY_ID:'TEST-CLOUD-KEY',PERSONAL_OS_STEP3_MAC_EXECUTOR_ID:'TEST-MAC',PERSONAL_OS_STEP3_MAC_KEY_ID:'TEST-MAC-KEY'});
 const evidence={schema_version:'personal_os.step7_evidence.v1',request_id:task.parameters.request_id,current_digest:'a'.repeat(64),current_status:'HANDOFF_CURRENT_MATERIALIZED',provider_read_status:'PROVIDER_READ_VERIFIED',ack_status:'NOT_OBSERVED',provider_write_performed:false};
 const result={schema_version:'personal_os.remote_procedure_result.v1',request_id:task.request_id,status:'COMPLETED',reason:null,attempts:1,read_back:{read_back:'PASS',evidence},authority_granted:false,provider_write_performed:false,spend_changed:false,published:false};const body={schema_version:'personal_os.remote_result_ack.v1',result};const ack={schema_version:'personal_os.remote_result_ack_envelope.v1',executor_id:'TEST-MAC',key_id:'TEST-MAC-KEY',issued_at:task.issued_at,nonce:'TEST-ACK-NONCE',body_sha256:digest(body),body};const message=['personal-os-result-ack-v1',ack.executor_id,ack.key_id,ack.issued_at,ack.nonce,ack.body_sha256].join('\n');ack.signature=crypto.sign(null,Buffer.from(message),mac.privateKey).toString('base64');
 assert.equal(store.acceptAck(ack).status,'ACKNOWLEDGED');assert.deepEqual(JSON.parse(JSON.stringify(store.result(task.request_id).result.read_back.evidence)),evidence);assert.equal(store.acceptAck(ack).duplicate,true);ack.body.result.read_back.evidence.current_digest='b'.repeat(64);assert.throws(()=>store.acceptAck(ack),/step3_ack_digest_invalid/);
});
