'use strict';
const test=require('node:test');
const assert=require('node:assert/strict');
const crypto=require('node:crypto');
const fs=require('node:fs');
const os=require('node:os');
const path=require('node:path');
const {validateRequest,signResult,requestMessage,digest}=require('../personal-os-step7-read-gateway');
function fixture(){const mac=crypto.generateKeyPairSync('ed25519'),rail=crypto.generateKeyPairSync('ed25519');const root=fs.mkdtempSync(path.join(os.tmpdir(),'step7-gw-'));const env={PERSONAL_OS_STEP3_STATE_PATH:root,PERSONAL_OS_STEP3_MAC_EXECUTOR_ID:'mac-step3',PERSONAL_OS_STEP3_MAC_KEY_ID:'mac-key-1',PERSONAL_OS_STEP3_MAC_PUBLIC_KEY_PEM:mac.publicKey.export({type:'spki',format:'pem'}),PERSONAL_OS_STEP3_EXECUTOR_ID:'railway-step3',PERSONAL_OS_STEP3_TASK_KEY_ID:'task-key-1',PERSONAL_OS_STEP3_TASK_SIGNING_PRIVATE_KEY_PEM:rail.privateKey.export({type:'pkcs8',format:'pem'})};return {mac,rail,env,root};}
function signed(mac,overrides={}){const body={request_id:'STEP7-READ-TEST-03',operation:'google_ads.read',campaign_id:'23276824770',...(overrides.body||{})};const e={schema_version:'personal_os.step7_read_request_envelope.v1',executor_id:'mac-step3',key_id:'mac-key-1',issued_at:'2026-10-08T05:00:00.000Z',nonce:'nonce-1',body_sha256:digest(body),signature:'',body,...overrides};e.signature=crypto.sign(null,Buffer.from(requestMessage(e)),mac.privateKey).toString('base64');return e;}
test('valid signed request is accepted once and does not need API key',()=>{const {mac,env,root}=fixture();const e=signed(mac);assert.equal(validateRequest(e,env,Date.parse('2026-10-08T05:00:30Z')).operation,'google_ads.read');assert.throws(()=>validateRequest(e,env,Date.parse('2026-10-08T05:00:30Z')),/step7_replayed_nonce/);assert.equal('PARMA_AGENT_API_KEY' in env,false);fs.rmSync(root,{recursive:true,force:true});});
test('tamper, stale, wrong identity and arbitrary operation fail closed',()=>{const {mac,env,root}=fixture();assert.throws(()=>validateRequest(signed(mac,{body:{operation:'google_ads.write'}}),env,Date.parse('2026-10-08T05:00:30Z')),/step7_operation_not_allowed/);assert.throws(()=>validateRequest(signed(mac,{executor_id:'evil'}),env,Date.parse('2026-10-08T05:00:30Z')),/step7_unknown_executor/);assert.throws(()=>validateRequest(signed(mac),env,Date.parse('2026-10-08T06:00:00Z')),/step7_stale_request/);const bad=signed(mac);bad.body.campaign_id='999';assert.throws(()=>validateRequest(bad,env,Date.parse('2026-10-08T05:00:30Z')),/step7_body_digest_mismatch/);fs.rmSync(root,{recursive:true,force:true});});
test('signed result preserves read-only safety flags and no secret fields',()=>{const {env,root}=fixture();const body={schema_version:'personal_os.step7_read_result.v1',request_id:'STEP7-READ-TEST-03',status:'COMPLETED',operation:'google_ads.read',source:'google_ads',read_back:'PASS',data:{campaign_id:'23276824770',impressions:1,clicks:0,cost_eur:0},authority_granted:false,provider_write_performed:false,credentials_read:false,spend_changed:false,published:false};const e=signResult(body,env,{issuedAt:'2026-10-08T05:00:00.000Z',nonce:'result-1'});const raw=JSON.stringify(e);for(const forbidden of ['PARMA_AGENT_API_KEY','authorization','refresh_token','access_token'])assert.equal(raw.includes(forbidden),false);assert.equal(e.body.provider_write_performed,false);fs.rmSync(root,{recursive:true,force:true});});
