const test=require("node:test");
const assert=require("node:assert/strict");
const {scoreSearchTerms,scoreKeywords,detectWaste,detectOpportunities,assessMatchTypes,simulateBudget,assessLandingContinuity,assessRsa,buildSafetyGate,buildExecutiveModel}=require("../preaccess-intelligence");

test("search and keyword scoring fail closed on low evidence",()=>{assert.equal(scoreSearchTerms([{clicks:1,cost_eur:1,conversions:0}])[0].intelligence.classification,"low_evidence");assert.equal(scoreKeywords([{clicks:2,cost_eur:2,conversions:0}])[0].intelligence.classification,"low_evidence");});
test("waste detector estimates only evidence-backed nonconverting cost",()=>{const w=detectWaste({searchTerms:[{search_term:"jobs",clicks:8,cost_eur:9,conversions:0}],keywords:[{keyword:"pizza",clicks:2,cost_eur:1,conversions:0}]});assert.equal(w.estimated_waste_eur,9);assert.equal(w.items.length,1);});
test("opportunity detector finds converting unmatched search terms",()=>{const o=detectOpportunities({searchTerms:[{search_term:"bio pizza berlin",matched_keyword:"pizza berlin",conversions:2,cost_eur:3,clicks:4}]});assert.equal(o[0].type,"keyword_expansion");assert.equal(o[0].confidence,"high");});
test("broad match warning requires meaningful traffic",()=>{const a=assessMatchTypes([{match_type:"BROAD",clicks:11,cost_eur:10,conversions:0}]);assert.equal(a.warnings[0].code,"BROAD_MATCH_WASTE_RISK");});
test("budget simulation never represents a write",()=>{const r=simulateBudget([{campaign:"Dinner",spend_eur:20,conversions:4,target_cpa_eur:10}])[0];assert.equal(r.simulated_delta_percent,20);assert.equal(r.simulation_only,true);assert.equal(r.requires_authorization,true);});
test("landing continuity detects shared commercial intent",()=>{const r=assessLandingContinuity({searchTerm:"bio pizza berlin",keyword:"bio pizza",adText:"Bio Pizza in Berlin Kreuzberg",landingText:"Reserviere Bio Pizza in Berlin"});assert.ok(r.score>=50);});
test("RSA analysis catches weak variation and intent coverage",()=>{const r=assessRsa({headlines:["Pizza Berlin","Pizza Berlin"],descriptions:["Jetzt reservieren"],intentTerms:["bio","kreuzberg"]});assert.equal(r.status,"attention_required");assert.ok(r.issues.includes("LOW_HEADLINE_VARIETY"));});
test("safety gate never permits autonomous writes pre-access",()=>{const g=buildSafetyGate({googleOk:true,ga4Ok:true,conversionIntegrity:{optimization_allowed:true},funnelStatus:"healthy",evidenceCount:10});assert.equal(g.automation_allowed,false);assert.equal(g.recommendation_mode,"proposal_only");});
test("executive model compresses diagnostic signals",()=>{const m=buildExecutiveModel({waste:{estimated_waste_eur:12,items:[{label:"jobs",reason:"waste"}]},opportunities:[{type:"keyword_expansion",term:"bio pizza"}],funnel:{status:"healthy"},conversionIntegrity:{status:"healthy"},safetyGate:{reasons:[]}});assert.equal(m.estimated_waste_eur,12);assert.equal(m.opportunity_count,1);assert.equal(m.automation_allowed,false);});
