'use strict';
const fs=require('node:fs');const path=require('node:path');
const loop=require('./autonomous-work-loop');const {validationPlan}=require('./risk-based-validation');
const FILE='parma-autonomous-work-state.json';
function statePath(env=process.env){return env.AUTONOMOUS_STATE_PATH||(env.RAILWAY_VOLUME_MOUNT_PATH?path.join(env.RAILWAY_VOLUME_MOUNT_PATH,FILE):path.join('/tmp',FILE));}
function storageStatus(env=process.env){const p=statePath(env);const durable=!p.startsWith('/tmp/');return{path:p,durable,source:env.AUTONOMOUS_STATE_PATH?'explicit_path':env.RAILWAY_VOLUME_MOUNT_PATH?'railway_volume':'default_tmp'};}
function sanitize(v){const s=JSON.stringify(v??{});if(/(password|secret|token|api[_-]?key|credential)/i.test(s))throw new Error('secret_shaped_state_rejected');return JSON.parse(s);}
function load(file=statePath()){if(!fs.existsSync(file))return null;try{return JSON.parse(fs.readFileSync(file,'utf8'));}catch{return null;}}
function save(state,file=statePath()){const clean=sanitize(state);fs.mkdirSync(path.dirname(file),{recursive:true});const tmp=file+'.tmp';fs.writeFileSync(tmp,JSON.stringify(clean)+'\n',{mode:0o600});fs.renameSync(tmp,file);const check=load(file);if(!check)throw new Error('autonomous_state_persistence_failed');return check;}
function classifyError(error){const code=String(error?.code||error?.message||'unknown').toLowerCase();if(/auth|permission|login|credential/.test(code))return'human';if(/timeout|rate|network|external/.test(code))return'external';return'fixable';}
async function runGoal({goal,tasks,executors={},context={},file=statePath(),maxSteps=50}={}){let state=load(file)||{version:1,goal:String(goal||''),tasks:(tasks||[]).map(t=>({...t,status:t.status||'pending',attempts:t.attempts||0,evidence:t.evidence||[]})),current_state:'READY',decisions:[],blockers:[],next_action:null};save(state,file);for(let step=0;step<maxSteps;step++){const d=loop.decide(state,context);state.current_state=d.state;state.next_action=d.task?.id||null;save(state,file);if(['DONE','NEEDS_HUMAN','BLOCKED_EXTERNAL'].includes(d.state))return state;const task=d.task;if(d.state==='VALIDATE_L2'){state.current_state='BLOCKED_EXTERNAL';state.blockers.push({task_id:task.id,type:'live_validation_required'});save(state,file);return state;}const exec=executors[task.kind];if(typeof exec!=='function'){state.current_state='BLOCKED_EXTERNAL';state.blockers.push({task_id:task.id,type:'executor_missing'});save(state,file);return state;}try{const plan=validationPlan(task.change||{});const result=await exec(task,{validation:plan});const after=loop.afterExecution(task,{...result,level2_required:plan.live_read_only_validation});if(after.state==='NEXT'){const found=state.tasks.find(x=>String(x.id)===task.id);found.status='done';found.evidence=[...(found.evidence||[]),...(result.evidence||[])];state.current_state='NEXT';save(state,file);continue;}if(after.state==='FIX'){const found=state.tasks.find(x=>String(x.id)===task.id);found.attempts=(found.attempts||0)+1;found.last_failure=String(result.reason||'l1_failed').slice(0,120);save(state,file);continue;}state.current_state=after.state;save(state,file);return state;}catch(error){const kind=classifyError(error);if(kind==='human')state.current_state='NEEDS_HUMAN';else if(kind==='external')state.current_state='BLOCKED_EXTERNAL';else{const found=state.tasks.find(x=>String(x.id)===task.id);found.attempts=(found.attempts||0)+1;if(found.attempts<Number(found.max_attempts||3)){save(state,file);continue;}state.current_state='BLOCKED_EXTERNAL';}state.blockers.push({task_id:task.id,type:kind});save(state,file);return state;}}state.current_state='BLOCKED_EXTERNAL';state.blockers.push({type:'max_steps_exceeded'});save(state,file);return state;}
module.exports={FILE,statePath,storageStatus,sanitize,load,save,classifyError,runGoal};
