'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {listSpecialists}=require('./specialist-registry');
const {summary:standingDelegationSummary}=require('./standing-delegation-policy');
const {conversionIntegrity}=require('./economic-ground-truth');
const {describeAction,listActions,writeAuthorized,spendAuthorized}=require('./action-registry');
const {requiredActionFor}=require('./autonomous-runtime-resume');
function newestDone(state){return state.objectives.flatMap(o=>o.tasks.map(t=>({objective_id:o.id,...t}))).filter(t=>t.status==='DONE').sort((a,b)=>String(b.completed_at||'').localeCompare(String(a.completed_at||'')))[0]||null;}
function latestBudgetCage(state){const rows=state.objectives.flatMap(o=>o.tasks.filter(t=>t.kind==='google_ads.execution_preflight'&&t.status==='DONE').flatMap(t=>(t.evidence||[]).map(e=>({completed_at:t.completed_at,cage:e.budget_cage})))).filter(x=>x.cage).sort((a,b)=>String(b.completed_at||'').localeCompare(String(a.completed_at||'')));return rows[0]?.cage||null;}
function lastMutationMetadata(env=process.env){const root=env.RAILWAY_VOLUME_MOUNT_PATH?path.join(env.RAILWAY_VOLUME_MOUNT_PATH,'google-controlled-execution'):null;if(!root||!fs.existsSync(root))return null;let newest=null;for(const name of fs.readdirSync(root)){if(!/^[a-f0-9]{64}\.json$/.test(name))continue;const file=path.join(root,name);try{const st=fs.statSync(file);if(!newest||st.mtimeMs>newest.mtimeMs)newest={execution_id:name.slice(0,-5),updated_at:st.mtime.toISOString(),mtimeMs:st.mtimeMs};}catch{}}if(!newest)return null;delete newest.mtimeMs;return newest;}
function latestShadowSourceHealth(env=process.env){const mount=env.RAILWAY_VOLUME_MOUNT_PATH;if(!mount)return null;const file=path.join(mount,'parma-shadow-history.json');try{const parsed=JSON.parse(fs.readFileSync(file,'utf8'));const rows=Array.isArray(parsed)?parsed:Array.isArray(parsed?.history)?parsed.history:[];const latest=rows.at(-1);if(!latest?.source_health)return null;return {observed_at:latest.generated_at||latest.id||null,google:Boolean(latest.source_health.google),ga4:Boolean(latest.source_health.ga4),meta:Boolean(latest.source_health.meta)};}catch{return null;}}
function taskView(objective,task){if(!task||!objective)return null;const action=describeAction(task.kind);return {objective_id:objective.id,id:task.id,kind:task.kind,status:task.status,attempts:task.attempts,max_attempts:task.max_attempts,specialist:action.specialist,ownership:{concurrency_key:action.concurrency,implemented:action.implemented},authorization:{mode:action.authorization,write:writeAuthorized(task.kind),spend:spendAuthorized(task.kind)},retry:task.retry||null,created_at:task.created_at||null,updated_at:task.updated_at||null,completed_at:task.completed_at||null};}
function nextEligible(objective){return objective?.tasks.find(t=>t.status==='PENDING'&&t.depends_on.every(id=>objective.tasks.some(x=>x.id===id&&x.status==='DONE')))||objective?.tasks.find(t=>t.status==='RETRY_WAIT'&&t.depends_on.every(id=>objective.tasks.some(x=>x.id===id&&x.status==='DONE')))||null;}
function buildControlTower({runtimeState,schedulerSnapshot=null,env=process.env}={}){
 const state=runtimeState;const active=state.objectives.filter(o=>['READY','RUNNING','RETRY_WAIT'].includes(o.status));const completed=state.objectives.filter(o=>o.status==='DONE');
 const activeObjective=active[0]||null;const currentTask=activeObjective?.tasks.find(t=>t.id===activeObjective.current_task_id)||null;const nextTask=nextEligible(activeObjective);
 const pendingHuman=state.objectives.flatMap(o=>o.tasks.filter(t=>t.status==='NEEDS_HUMAN').map(t=>{const a=describeAction(t.kind);return {objective_id:o.id,task_id:t.id,kind:t.kind,specialist:a.specialist,reason:t.stop_reason,required_action:t.required_action||requiredActionFor(t,'NEEDS_HUMAN',t.stop_reason),resume_supported:true,updated_at:t.updated_at};}));
 const blocked=state.objectives.flatMap(o=>o.tasks.filter(t=>t.status==='BLOCKED_EXTERNAL').map(t=>{const a=describeAction(t.kind);return {objective_id:o.id,task_id:t.id,kind:t.kind,specialist:a.specialist,reason:t.stop_reason,required_action:t.required_action||requiredActionFor(t,'BLOCKED_EXTERNAL',t.stop_reason),resume_supported:true,retry:t.retry,updated_at:t.updated_at};}));
 const retry=state.objectives.flatMap(o=>o.tasks.filter(t=>t.status==='RETRY_WAIT').map(t=>({...taskView(o,t),next_attempt_at:t.retry?.next_attempt_at||null})));
 const last=newestDone(state),shadow=latestShadowSourceHealth(env);const lastObjective=last?state.objectives.find(o=>o.id===last.objective_id):null;
 return {schema:'parma.control_tower.v1',runner:{status:state.runner.status,kill_switch:state.runner.kill_switch,heartbeat_at:state.runner.heartbeat_at,last_error:state.runner.last_error},objectives:{active:active.map(o=>({id:o.id,status:o.status,current_task_id:o.current_task_id,next_action:o.next_action,created_at:o.created_at,updated_at:o.updated_at,required_action:o.required_action||null})),completed_count:completed.length,total_count:state.objectives.length},current_task:taskView(activeObjective,currentTask),next_task:taskView(activeObjective,nextTask),last_successful_action:last?taskView(lastObjective,last):null,last_mutation:lastMutationMetadata(env),evidence_timestamp:last?.completed_at||null,pending_needs_human:pendingHuman,blocked_external:blocked,retry_state:retry,guardrails:{standing_delegation:standingDelegationSummary(),budget_cage:latestBudgetCage(state),conversion_integrity:conversionIntegrity,default_external_writes_allowed:false,default_spend_allowed:false},recurring:schedulerSnapshot,specialists:listSpecialists(),action_registry:listActions(),source_health:{shadow:shadow,google_ads:state.objectives.some(o=>o.tasks.some(t=>t.kind==='google_ads.read_campaign'&&t.status==='DONE'))?'last_read_success':'no_successful_runtime_read',orderbird:'separate_provider_state'}};
}
module.exports={buildControlTower,lastMutationMetadata,latestBudgetCage,latestShadowSourceHealth,taskView};
