'use strict';
const fs=require('node:fs');
const path=require('node:path');
const {listSpecialists}=require('./specialist-registry');
const {summary:standingDelegationSummary}=require('./standing-delegation-policy');
const {conversionIntegrity}=require('./economic-ground-truth');
function newestDone(state){return state.objectives.flatMap(o=>o.tasks.map(t=>({objective_id:o.id,...t}))).filter(t=>t.status==='DONE').sort((a,b)=>String(b.completed_at||'').localeCompare(String(a.completed_at||'')))[0]||null;}
function latestBudgetCage(state){const rows=state.objectives.flatMap(o=>o.tasks.filter(t=>t.kind==='google_ads.execution_preflight'&&t.status==='DONE').flatMap(t=>(t.evidence||[]).map(e=>({completed_at:t.completed_at,cage:e.budget_cage})))).filter(x=>x.cage).sort((a,b)=>String(b.completed_at||'').localeCompare(String(a.completed_at||'')));return rows[0]?.cage||null;}
function lastMutationMetadata(env=process.env){const root=env.RAILWAY_VOLUME_MOUNT_PATH?path.join(env.RAILWAY_VOLUME_MOUNT_PATH,'google-controlled-execution'):null;if(!root||!fs.existsSync(root))return null;let newest=null;for(const name of fs.readdirSync(root)){if(!/^[a-f0-9]{64}\.json$/.test(name))continue;const file=path.join(root,name);try{const st=fs.statSync(file);if(!newest||st.mtimeMs>newest.mtimeMs)newest={execution_id:name.slice(0,-5),updated_at:st.mtime.toISOString(),mtimeMs:st.mtimeMs};}catch{}}if(!newest)return null;delete newest.mtimeMs;return newest;}
function buildControlTower({runtimeState,schedulerSnapshot=null,env=process.env}={}){const state=runtimeState;const active=state.objectives.filter(o=>['READY','RUNNING','RETRY_WAIT'].includes(o.status));const completed=state.objectives.filter(o=>o.status==='DONE');const current=active.flatMap(o=>o.tasks.filter(t=>t.id===o.current_task_id).map(t=>({objective_id:o.id,id:t.id,kind:t.kind,status:t.status,attempts:t.attempts}))).at(0)||null;const pendingHuman=state.objectives.flatMap(o=>o.tasks.filter(t=>t.status==='NEEDS_HUMAN').map(t=>({objective_id:o.id,task_id:t.id,kind:t.kind,reason:t.stop_reason})));const blocked=state.objectives.flatMap(o=>o.tasks.filter(t=>t.status==='BLOCKED_EXTERNAL').map(t=>({objective_id:o.id,task_id:t.id,kind:t.kind,reason:t.stop_reason,retry:t.retry})));const retry=state.objectives.flatMap(o=>o.tasks.filter(t=>t.status==='RETRY_WAIT').map(t=>({objective_id:o.id,task_id:t.id,kind:t.kind,retry:t.retry})));const last=newestDone(state);return {schema:'parma.control_tower.v1',runner:{status:state.runner.status,kill_switch:state.runner.kill_switch,heartbeat_at:state.runner.heartbeat_at,last_error:state.runner.last_error},objectives:{active:active.map(o=>({id:o.id,status:o.status,current_task_id:o.current_task_id,next_action:o.next_action})),completed_count:completed.length,total_count:state.objectives.length},current_task:current,next_task:active.length?active[0].tasks.find(t=>t.status==='PENDING'&&t.depends_on.every(id=>active[0].tasks.some(x=>x.id===id&&x.status==='DONE')))?.id||null:null,last_successful_action:last?{objective_id:last.objective_id,task_id:last.id,kind:last.kind,completed_at:last.completed_at}:null,last_mutation:lastMutationMetadata(env),evidence_timestamp:last?.completed_at||null,pending_needs_human:pendingHuman,blocked_external:blocked,retry_state:retry,guardrails:{standing_delegation:standingDelegationSummary(),budget_cage:latestBudgetCage(state),conversion_integrity:conversionIntegrity},recurring:schedulerSnapshot,specialists:listSpecialists(),source_health:{google_ads:state.objectives.some(o=>o.tasks.some(t=>t.kind==='google_ads.read_campaign'&&t.status==='DONE'))?'last_read_success':'no_successful_runtime_read',orderbird:'awaiting_official_provider_path'}};}
module.exports={buildControlTower,lastMutationMetadata,latestBudgetCage};
